### PR TITLE
#161240710 Write tests for attemptClientLogin method

### PR DESCRIPTION
**Pull request by chukwuemekachm**
#### What does this PR do?
- This PR adds tests for attemptClientLogin function in `apps/admin/src/routes/index.tsx`
#### Description of Task to be completed?
- Export named Routes component
- Add tests for attemptClientLogin in index.test.tsx
#### How should this be manually tested?
- Run `npm test`
- Observe the test in `apps/admin/src/routes/index.test.tsx` passing
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
- [#161240710](https://www.pivotaltracker.com/story/show/161240710)
#### Screenshots (if appropriate)
- None
#### Questions:
- N/A

### CODE REVIEW

**Comment by matthewepler** [comment]
@chukwuemekachm The tests look good, but I get failing errors. Maybe I have users in my database with the same email as the data in your tests? Is there a way to setup and teardown the test or use a dynamic email address (with timestamp in the string?) so that there's never a match?

Take a closer look at the error. I could be wrong about what's making the tests fail. I only had a chance to look at the basic error descriptions. 

```
{ Error: Command failed: npm run test
PASS __tests__/UserRepository.test.ts (10.326s)
  ● Console

    console.log node_modules/winston/lib/winston/transports/console.js:62
      {"level":"info","message":"UserRepository.ts @ save(): newUser = [object Object]"}


PASS __tests__/TaskRepository.test.ts (10.839s)
FAIL __tests__/Email.test.ts (11.846s)
  ● Console

    console.log node_modules/winston/lib/winston/transports/console.js:62
      {"level":"error","message":"UserRepository.ts @ save(): Could not create user >> duplicate key value violates unique constraint \"user_email_unique\""}


  ● Email service › sets API key

    Failed: "Could not create user (error: duplicate key value violates unique constraint \"user_email_unique\")"

      17 |
      18 | describe('Email service', () => {
    > 19 |   beforeAll(async () => {
         |   ^
      20 |     sendgridEnabled = process.env.SENDGRID_ENABLED;
      21 |     baseUrl = process.env.BASE_URL;
      22 |     process.env.SENDGRID_ENABLED = 'true';

      at Env.beforeAll (node_modules/jest/node_modules/jest-jasmine2/build/jasmine_async.js:55:24)
      at Suite.<anonymous> (__tests__/Email.test.ts:19:3)
      at Object.<anonymous> (__tests__/Email.test.ts:18:1)

  ● Email service › sets substitution wrappers

    Failed: "Could not create user (error: duplicate key value violates unique constraint \"user_email_unique\")"

      17 |
      18 | describe('Email service', () => {
    > 19 |   beforeAll(async () => {
         |   ^
      20 |     sendgridEnabled = process.env.SENDGRID_ENABLED;
      21 |     baseUrl = process.env.BASE_URL;
      22 |     process.env.SENDGRID_ENABLED = 'true';

      at Env.beforeAll (node_modules/jest/node_modules/jest-jasmine2/build/jasmine_async.js:55:24)
      at Suite.<anonymous> (__tests__/Email.test.ts:19:3)
      at Object.<anonymous> (__tests__/Email.test.ts:18:1)

  ● Email service › extracts client params

    Failed: "Could not create user (error: duplicate key value violates unique constraint \"user_email_unique\")"

      17 |
      18 | describe('Email service', () => {
    > 19 |   beforeAll(async () => {
         |   ^
      20 |     sendgridEnabled = process.env.SENDGRID_ENABLED;
      21 |     baseUrl = process.env.BASE_URL;
      22 |     process.env.SENDGRID_ENABLED = 'true';

      at Env.beforeAll (node_modules/jest/node_modules/jest-jasmine2/build/jasmine_async.js:55:24)
      at Suite.<anonymous> (__tests__/Email.test.ts:19:3)
      at Object.<anonymous> (__tests__/Email.test.ts:18:1)

  ● Email service › extracts client params

    TypeError: Cannot read property 'id' of undefined

      73 |       email: 'client@example.com',
      74 |       org_id: org.id,
    > 75 |       coach_id: coach.id,
         |                         ^
      76 |       plan_url: 'https://example.com/my-tasks',
      77 |     });
      78 |     expect(mockSendgridClient.send).toHaveBeenCalledWith({

      at __tests__/Email.test.ts:75:25
      at step (__tests__/Email.test.ts:6:59)
      at Object.next (__tests__/Email.test.ts:6:59)
      at __tests__/Email.test.ts:6:59
      at Object.<anonymous>.__awaiter (__tests__/Email.test.ts:6:59)
      at Object.<anonymous> (__tests__/Email.test.ts:69:32)
```

**Comment by chukwuemekachm** [comment]
Thank you @matthewepler, I will modify the tests and push.

**Comment by chukwuemekachm** [comment]
Hi @matthewepler, I've modified the tests and I'm using timestamps for the email to ensure that it never conflicts with any previous ones. Please pull the branch and re-run them again.
Thanks.

**Comment by Oluwafayokemi** [comment]
> @chukwuemekachm getting a new error. A strange one! It seems like nothing, but it is causing the test to fail. Have you asked a colleague to run the tests on your branch? Maybe it's just me...
> 
> screen shot 2018-10-25 at 12 20 53 pm

Good morning @matthewepler I pulled @chukwuemekachm branch and ran npm test. It passes. These are the screen shots
image
image

**Comment by chukwuemekachm** [comment]
Hi @matthewepler, I think the issue might be with your local setup. I've tried to reproduce the errors on my own machine to no avail. I also asked some other teammates to pull the branch and run the tests on their local machines which they did and it passed.

**Comment by matthewepler** [comment]
2 colleagues show passing tests, so I'm merging. Thanks @yomigeek and @Oluwafayokemi !

**Pull request merged**
